# Generated by Django 5.1.4 on 2025-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_payslip_month_integer_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employee_name',
            field=models.CharField(default='Name', max_length=300),
            preserve_default=False,
        ),
    ]
