# Generated by Django 5.1.4 on 2025-05-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='employee_name',
        ),
    ]
